os: osx
osx_image: xcode13.1
language: swift
script: 
  - xcodebuild clean build test -project ARPlacer/ARPlacer.xcodeproj -scheme "ARPlacer" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" ONLY_ACTIVE_ARCH=YES


